import type { AdminTutorReview, Booking, ReportPoint, Student, Tutor } from "@/lib/types";

export const tutors: Tutor[] = [
  {
    id: "aisyah-rahman",
    name: "Cikgu Aisyah Rahman",
    initials: "AR",
    title: "Pakar Matematik SPM",
    state: "Kuala Lumpur",
    district: "Kuala Lumpur",
    distanceKm: 5,
    subjects: ["Matematik", "Matematik Tambahan"],
    levels: ["SPM"],
    curriculums: ["KSSM"],
    languages: ["Bahasa Melayu", "English"],
    gender: "Perempuan",
    modes: ["Online", "Fizikal"],
    price: 75,
    experienceYears: 9,
    professionalScore: 94,
    rating: 4.9,
    reviewCount: 86,
    responseMinutes: 18,
    completionRate: 98,
    cancellationRate: 1.1,
    badges: ["Identiti Disahkan", "Pakar SPM", "Tutor Pilihan Ibu Bapa"],
    slots: [
      { id: "ar-1", date: "Isnin", day: "22 Jul", time: "8:00 malam", mode: "Online", status: "Available" },
      { id: "ar-2", date: "Rabu", day: "24 Jul", time: "6:00 petang", mode: "Fizikal", status: "Available" },
      { id: "ar-3", date: "Sabtu", day: "27 Jul", time: "10:00 pagi", mode: "Online", status: "Booked" },
    ],
    scoreBreakdown: { kelulusan: 96, pengalaman: 92, kelasSelesai: 94, ketepatanMasa: 98, respons: 97, prestasiMurid: 91 },
    bio: "Membantu murid lemah asas algebra membina keyakinan melalui latihan bertahap dan analisis kesilapan.",
    highlight: "86 keluarga mengekalkan kelas selepas sesi percubaan.",
    verified: true,
  },
  {
    id: "hafiz-iskandar",
    name: "Cikgu Hafiz Iskandar",
    initials: "HI",
    title: "Jurulatih Sains Menengah",
    state: "Selangor",
    district: "Shah Alam",
    distanceKm: 18,
    subjects: ["Sains"],
    levels: ["Tingkatan 1-3"],
    curriculums: ["KSSM"],
    languages: ["Bahasa Melayu"],
    gender: "Lelaki",
    modes: ["Online", "Fizikal"],
    price: 65,
    experienceYears: 7,
    professionalScore: 88,
    rating: 4.7,
    reviewCount: 61,
    responseMinutes: 35,
    completionRate: 96,
    cancellationRate: 2,
    badges: ["Sijil Disahkan", "Respons Pantas"],
    slots: [
      { id: "hi-1", date: "Selasa", day: "23 Jul", time: "7:30 malam", mode: "Online", status: "Available" },
      { id: "hi-2", date: "Khamis", day: "25 Jul", time: "5:30 petang", mode: "Fizikal", status: "Available" },
    ],
    scoreBreakdown: { kelulusan: 84, pengalaman: 86, kelasSelesai: 91, ketepatanMasa: 94, respons: 89, prestasiMurid: 85 },
    bio: "Menggunakan demonstrasi ringkas dan peta konsep untuk topik Sains Tingkatan 1-3.",
    highlight: "Sesuai untuk murid yang perlukan penerangan visual.",
    verified: true,
  },
  {
    id: "sarah-lim",
    name: "Teacher Sarah Lim",
    initials: "SL",
    title: "English Speaking Coach",
    state: "Pulau Pinang",
    district: "Timur Laut",
    distanceKm: 2,
    subjects: ["Bahasa Inggeris"],
    levels: ["IGCSE", "SPM"],
    curriculums: ["IGCSE", "KSSM"],
    languages: ["English", "Bahasa Melayu"],
    gender: "Perempuan",
    modes: ["Online"],
    price: 90,
    experienceYears: 11,
    professionalScore: 91,
    rating: 4.8,
    reviewCount: 72,
    responseMinutes: 22,
    completionRate: 99,
    cancellationRate: 0.8,
    badges: ["Sijil Disahkan", "Kehadiran Cemerlang"],
    slots: [
      { id: "sl-1", date: "Isnin", day: "22 Jul", time: "5:00 petang", mode: "Online", status: "Available" },
      { id: "sl-2", date: "Jumaat", day: "26 Jul", time: "8:30 malam", mode: "Online", status: "Temporarily held" },
    ],
    scoreBreakdown: { kelulusan: 93, pengalaman: 95, kelasSelesai: 88, ketepatanMasa: 97, respons: 95, prestasiMurid: 90 },
    bio: "Fokus kepada grammar, writing structure dan confidence untuk murid IGCSE.",
    highlight: "Murid biasanya naik satu band writing selepas 10 minggu.",
    verified: true,
  },
  {
    id: "kumar-raj",
    name: "Mr Kumar Raj",
    initials: "KR",
    title: "Guru Fizik Berpengalaman",
    state: "Johor",
    district: "Johor Bahru",
    distanceKm: 9,
    subjects: ["Fizik"],
    levels: ["SPM"],
    curriculums: ["KSSM"],
    languages: ["English", "Bahasa Melayu", "Tamil"],
    gender: "Lelaki",
    modes: ["Online", "Fizikal"],
    price: 95,
    experienceYears: 14,
    professionalScore: 89,
    rating: 4.6,
    reviewCount: 55,
    responseMinutes: 40,
    completionRate: 97,
    cancellationRate: 1.7,
    badges: ["Guru Berdaftar", "Sijil Disahkan"],
    slots: [{ id: "kr-1", date: "Khamis", day: "25 Jul", time: "8:30 malam", mode: "Online", status: "Temporarily held" }],
    scoreBreakdown: { kelulusan: 90, pengalaman: 96, kelasSelesai: 87, ketepatanMasa: 92, respons: 84, prestasiMurid: 88 },
    bio: "Menerangkan konsep fizik melalui analogi harian dan soalan berformat peperiksaan.",
    highlight: "Kuat untuk topik daya, gerakan dan elektrik.",
    verified: true,
  },
  {
    id: "nurul-iman",
    name: "Cikgu Nurul Iman",
    initials: "NI",
    title: "Tutor Bahasa Melayu UPSR/SPM",
    state: "Perak",
    district: "Ipoh",
    distanceKm: 6,
    subjects: ["Bahasa Melayu"],
    levels: ["Tahun 4-6", "SPM"],
    curriculums: ["KSSR", "KSSM"],
    languages: ["Bahasa Melayu"],
    gender: "Perempuan",
    modes: ["Online", "Fizikal"],
    price: 60,
    experienceYears: 8,
    professionalScore: 84,
    rating: 4.6,
    reviewCount: 43,
    responseMinutes: 28,
    completionRate: 96,
    cancellationRate: 1.9,
    badges: ["Identiti Disahkan"],
    slots: [{ id: "ni-1", date: "Sabtu", day: "27 Jul", time: "10:00 pagi", mode: "Fizikal", status: "Available" }],
    scoreBreakdown: { kelulusan: 82, pengalaman: 85, kelasSelesai: 82, ketepatanMasa: 90, respons: 88, prestasiMurid: 84 },
    bio: "Membimbing karangan, tatabahasa dan pemahaman dengan rubrik yang jelas.",
    highlight: "Murid menulis karangan lebih teratur dalam masa 4 minggu.",
    verified: true,
  },
  {
    id: "amir-faiz",
    name: "Dr Amir Faiz",
    initials: "AF",
    title: "Kimia SPM dan Pra-U",
    state: "Negeri Sembilan",
    district: "Seremban",
    distanceKm: 13,
    subjects: ["Kimia"],
    levels: ["SPM"],
    curriculums: ["KSSM"],
    languages: ["Bahasa Melayu", "English"],
    gender: "Lelaki",
    modes: ["Online"],
    price: 120,
    experienceYears: 15,
    professionalScore: 92,
    rating: 4.7,
    reviewCount: 38,
    responseMinutes: 60,
    completionRate: 94,
    cancellationRate: 2.6,
    badges: ["Sijil Disahkan", "Pakar SPM"],
    slots: [{ id: "af-1", date: "Selasa", day: "23 Jul", time: "9:00 malam", mode: "Online", status: "Available" }],
    scoreBreakdown: { kelulusan: 100, pengalaman: 97, kelasSelesai: 84, ketepatanMasa: 89, respons: 78, prestasiMurid: 93 },
    bio: "Bekas pensyarah kolej yang memberi penekanan kepada stoikiometri dan eksperimen.",
    highlight: "Sesuai untuk murid sasaran A dan A+.",
    verified: true,
  },
  {
    id: "lina-zulkifli",
    name: "Cikgu Lina Zulkifli",
    initials: "LZ",
    title: "Guru Matematik Rendah",
    state: "Selangor",
    district: "Petaling",
    distanceKm: 7,
    subjects: ["Matematik"],
    levels: ["Tahun 4-6"],
    curriculums: ["KSSR"],
    languages: ["Bahasa Melayu"],
    gender: "Perempuan",
    modes: ["Online", "Fizikal"],
    price: 50,
    experienceYears: 6,
    professionalScore: 87,
    rating: 4.9,
    reviewCount: 47,
    responseMinutes: 16,
    completionRate: 99,
    cancellationRate: 0.5,
    badges: ["Respons Pantas", "Kehadiran Cemerlang"],
    slots: [{ id: "lz-1", date: "Isnin", day: "22 Jul", time: "3:00 petang", mode: "Fizikal", status: "Available" }],
    scoreBreakdown: { kelulusan: 80, pengalaman: 83, kelasSelesai: 92, ketepatanMasa: 99, respons: 98, prestasiMurid: 82 },
    bio: "Kelas ceria dan tersusun untuk murid Tahun 4-6 yang perlukan asas kukuh.",
    highlight: "Kuat untuk nombor bulat, pecahan dan penyelesaian masalah.",
    verified: true,
  },
  {
    id: "azlan-omar",
    name: "Cikgu Azlan Omar",
    initials: "AO",
    title: "Calon Tutor Sejarah",
    state: "Kedah",
    district: "Alor Setar",
    distanceKm: 11,
    subjects: ["Sejarah"],
    levels: ["SPM"],
    curriculums: ["KSSM"],
    languages: ["Bahasa Melayu"],
    gender: "Lelaki",
    modes: ["Online", "Fizikal"],
    price: 52,
    experienceYears: 4,
    professionalScore: 69,
    rating: 0,
    reviewCount: 0,
    responseMinutes: 80,
    completionRate: 90,
    cancellationRate: 4,
    badges: ["Menunggu Pengesahan"],
    slots: [{ id: "ao-1", date: "Rabu", day: "24 Jul", time: "8:00 malam", mode: "Online", status: "Unavailable" }],
    scoreBreakdown: { kelulusan: 72, pengalaman: 66, kelasSelesai: 55, ketepatanMasa: 80, respons: 64, prestasiMurid: 58 },
    bio: "Mengaitkan fakta sejarah dengan kronologi dan latihan esei pendek.",
    highlight: "Profil sedang disemak oleh pejabat Tutor2U.",
    verified: false,
  },
  {
    id: "priyaa-menon",
    name: "Teacher Priyaa Menon",
    initials: "PM",
    title: "IGCSE Mathematics Specialist",
    state: "Kuala Lumpur",
    district: "Kuala Lumpur",
    distanceKm: 4,
    subjects: ["Matematik"],
    levels: ["IGCSE"],
    curriculums: ["IGCSE"],
    languages: ["English"],
    gender: "Perempuan",
    modes: ["Online"],
    price: 110,
    experienceYears: 10,
    professionalScore: 93,
    rating: 4.8,
    reviewCount: 49,
    responseMinutes: 25,
    completionRate: 97,
    cancellationRate: 1.5,
    badges: ["Sijil Disahkan", "Tutor Pilihan Ibu Bapa"],
    slots: [{ id: "pm-1", date: "Rabu", day: "24 Jul", time: "8:00 malam", mode: "Online", status: "Available" }],
    scoreBreakdown: { kelulusan: 97, pengalaman: 90, kelasSelesai: 89, ketepatanMasa: 94, respons: 96, prestasiMurid: 92 },
    bio: "Menyediakan latihan topical, checkpoint dan mock test untuk murid IGCSE.",
    highlight: "Sesuai untuk keluarga antarabangsa di KL.",
    verified: true,
  },
  {
    id: "hakim-yusof",
    name: "Cikgu Hakim Yusof",
    initials: "HY",
    title: "Tutor Sains Online",
    state: "Kelantan",
    district: "Kota Bharu",
    distanceKm: 16,
    subjects: ["Sains"],
    levels: ["Tingkatan 1-3"],
    curriculums: ["KSSM"],
    languages: ["Bahasa Melayu"],
    gender: "Lelaki",
    modes: ["Online"],
    price: 45,
    experienceYears: 3,
    professionalScore: 58,
    rating: 0,
    reviewCount: 0,
    responseMinutes: 120,
    completionRate: 89,
    cancellationRate: 5.2,
    badges: ["Perlu Pembetulan"],
    slots: [{ id: "hy-1", date: "Jumaat", day: "26 Jul", time: "9:00 malam", mode: "Online", status: "Unavailable" }],
    scoreBreakdown: { kelulusan: 65, pengalaman: 50, kelasSelesai: 40, ketepatanMasa: 75, respons: 54, prestasiMurid: 48 },
    bio: "Profil sedang dilengkapkan selepas semakan dokumen.",
    highlight: "Belum tersedia untuk tempahan awam.",
    verified: false,
  },
  {
    id: "nadia-salleh",
    name: "Cikgu Nadia Salleh",
    initials: "NS",
    title: "Pakar Add Math SPM",
    state: "Selangor",
    district: "Subang Jaya",
    distanceKm: 12,
    subjects: ["Matematik Tambahan"],
    levels: ["SPM"],
    curriculums: ["KSSM"],
    languages: ["Bahasa Melayu", "English"],
    gender: "Perempuan",
    modes: ["Online", "Fizikal"],
    price: 100,
    experienceYears: 12,
    professionalScore: 96,
    rating: 5,
    reviewCount: 91,
    responseMinutes: 14,
    completionRate: 99,
    cancellationRate: 0.7,
    badges: ["Guru Berdaftar", "Pakar SPM", "Respons Pantas"],
    slots: [{ id: "ns-1", date: "Selasa", day: "23 Jul", time: "6:30 petang", mode: "Hibrid", status: "Available" }],
    scoreBreakdown: { kelulusan: 98, pengalaman: 96, kelasSelesai: 95, ketepatanMasa: 99, respons: 99, prestasiMurid: 94 },
    bio: "Strategi step-by-step untuk fungsi, kalkulus asas dan soalan KBAT.",
    highlight: "Tutor tertinggi Professional Score minggu ini.",
    verified: true,
  },
  {
    id: "wei-jian",
    name: "Teacher Wei Jian",
    initials: "WJ",
    title: "English and Science Bilingual Tutor",
    state: "Sabah",
    district: "Kota Kinabalu",
    distanceKm: 10,
    subjects: ["Bahasa Inggeris", "Sains"],
    levels: ["Tingkatan 1-3"],
    curriculums: ["KSSM"],
    languages: ["Mandarin", "English", "Bahasa Melayu"],
    gender: "Lelaki",
    modes: ["Online", "Fizikal"],
    price: 68,
    experienceYears: 5,
    professionalScore: 82,
    rating: 4.5,
    reviewCount: 27,
    responseMinutes: 32,
    completionRate: 93,
    cancellationRate: 2.8,
    badges: ["Identiti Disahkan"],
    slots: [{ id: "wj-1", date: "Sabtu", day: "27 Jul", time: "2:00 petang", mode: "Online", status: "Available" }],
    scoreBreakdown: { kelulusan: 78, pengalaman: 76, kelasSelesai: 80, ketepatanMasa: 86, respons: 90, prestasiMurid: 78 },
    bio: "Menggabungkan penerangan dwibahasa untuk murid yang bertukar dari sekolah Cina ke KSSM.",
    highlight: "Pilihan baik untuk kelas peralihan bahasa.",
    verified: true,
  },
];

export const students: Student[] = [
  { id: "adam", name: "Adam Faris", level: "SPM", curriculum: "KSSM", school: "SMK Taman Tun", focus: "Add Math dan teknik menjawab" },
  { id: "sofia", name: "Sofia Hana", level: "Tahun 4-6", curriculum: "KSSR", school: "SK Bukit Damansara", focus: "Pecahan dan kefahaman nombor" },
  { id: "irfan", name: "Irfan Danial", level: "Tingkatan 1-3", curriculum: "KSSM", school: "SMK Seksyen 9", focus: "Sains topikal" },
  { id: "chloe", name: "Chloe Tan", level: "IGCSE", curriculum: "IGCSE", school: "Penang International School", focus: "Writing dan speaking" },
  { id: "ryan", name: "Ryan Tan", level: "Tahun 4-6", curriculum: "KSSR", school: "SJKC Hun Bin", focus: "Sains eksperimen" },
];

export const parentBookings: Booking[] = [
  { id: "bk-1", tutorName: "Cikgu Aisyah Rahman", studentName: "Adam Faris", subject: "Matematik Tambahan", mode: "Online", status: "Confirmed", nextSession: "22 Jul, 8:00 malam", pin: "4286" },
  { id: "bk-2", tutorName: "Cikgu Hafiz Iskandar", studentName: "Irfan Danial", subject: "Sains", mode: "Fizikal", status: "Completed", nextSession: "Selesai 2 hari lepas", pin: "7391" },
  { id: "bk-3", tutorName: "Teacher Sarah Lim", studentName: "Chloe Tan", subject: "Bahasa Inggeris", mode: "Online", status: "Pending tutor confirmation", nextSession: "25 Jul, 5:00 petang", pin: "1184" },
];

export const progressSeries: ReportPoint[] = [
  { label: "Mac", markah: 52, kehadiran: 82, jam: 6 },
  { label: "Apr", markah: 58, kehadiran: 88, jam: 8 },
  { label: "Mei", markah: 63, kehadiran: 91, jam: 10 },
  { label: "Jun", markah: 68, kehadiran: 94, jam: 12 },
  { label: "Jul", markah: 74, kehadiran: 96, jam: 14 },
];

export const topicMastery = [
  { topic: "Fungsi", mastery: 72 },
  { topic: "Algebra", mastery: 68 },
  { topic: "Graf", mastery: 58 },
  { topic: "KBAT", mastery: 46 },
  { topic: "Kalkulus asas", mastery: 64 },
];

export const tutorEarnings = [
  { month: "Mac", gross: 2180, commission: 327, net: 1853 },
  { month: "Apr", gross: 2560, commission: 384, net: 2176 },
  { month: "Mei", gross: 2840, commission: 426, net: 2414 },
  { month: "Jun", gross: 3120, commission: 468, net: 2652 },
  { month: "Jul", gross: 3380, commission: 507, net: 2873 },
];

export const adminTutorReviews: AdminTutorReview[] = [
  { id: "azlan-omar", name: "Cikgu Azlan Omar", state: "Kedah", subject: "Sejarah", status: "Menunggu", documents: ["Kad Pengenalan", "Ijazah"], risk: "Sederhana" },
  { id: "hakim-yusof", name: "Cikgu Hakim Yusof", state: "Kelantan", subject: "Sains", status: "Perlu pembetulan", documents: ["Sijil Akademik kabur"], risk: "Tinggi" },
  { id: "nadia-salleh", name: "Cikgu Nadia Salleh", state: "Selangor", subject: "Matematik Tambahan", status: "Diluluskan", documents: ["Kad Pengenalan", "Sijil Pendidikan"], risk: "Rendah" },
];

export const adminStats = [
  { label: "Tutor aktif", value: "10", trend: "+2 minggu ini" },
  { label: "Menunggu pengesahan", value: "2", trend: "1 perlu pembetulan" },
  { label: "Pelanggan aktif", value: "3", trend: "5 murid dipantau" },
  { label: "Tempahan hari ini", value: "7", trend: "3 belum disahkan" },
  { label: "Laporan belum dihantar", value: "4", trend: "2 melebihi SLA" },
  { label: "Aduan aktif", value: "1", trend: "Reschedule requested" },
  { label: "Jumlah jualan", value: "RM18.4k", trend: "+12% bulan ini" },
  { label: "Komisen platform", value: "RM2.76k", trend: "15% blended" },
  { label: "Bayaran tertunggak", value: "RM3.1k", trend: "5 payout pending" },
];

export const subjects = Array.from(new Set(tutors.flatMap((tutor) => tutor.subjects))).sort();
export const states = Array.from(new Set(tutors.map((tutor) => tutor.state))).sort();
export const levels = Array.from(new Set(tutors.flatMap((tutor) => tutor.levels))).sort();
export const curriculums = Array.from(new Set(tutors.flatMap((tutor) => tutor.curriculums))).sort();
