import type { TutorApplication } from "@/lib/tutor-onboarding/types";

export const demoTutorApplications: TutorApplication[] = [
  {
    id: "app-aisyah-2026",
    ownerProfileId: "tutor-aisyah-profile",
    tutorProfileId: "tp-aisyah",
    status: "submitted",
    completionPercent: 96,
    submittedAt: "2026-07-18T09:45:00+08:00",
    updatedAt: "2026-07-18T09:45:00+08:00",
    risk: "low",
    personal: {
      fullName: "Nur Aisyah Rahman",
      displayName: "Cikgu Aisyah Rahman",
      gender: "female",
      dateOfBirth: "1990-04-12",
      nationality: "Malaysia",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      postcode: "50480",
      preferredLanguage: "Bahasa Melayu",
      shortBiography: {
        ms: "Guru Matematik berpengalaman yang membantu murid SPM membina asas algebra dan keyakinan menjawab soalan KBAT.",
        en: "Experienced Mathematics teacher helping SPM learners strengthen algebra foundations and exam confidence.",
      },
    },
    identity: {
      documentType: "mykad",
      maskedIdentificationNumber: "900412-14-****",
      consent: true,
    },
    qualifications: [
      {
        id: "qual-aisyah-degree",
        level: "Sarjana Muda",
        title: "Ijazah Sarjana Muda Pendidikan Matematik",
        institution: "Universiti Malaya",
        fieldOfStudy: "Pendidikan Matematik",
        graduationYear: 2013,
        certificateName: "degree-certificate.pdf",
        verificationStatus: "submitted",
        adminNotes: {
          ms: "Sijil jelas dan menunggu semakan akhir.",
          en: "Certificate is clear and awaiting final review.",
        },
      },
    ],
    experience: {
      years: 9,
      currentOccupation: "Guru sekolah menengah",
      isSchoolTeacher: true,
      teachingInstitution: "SMK sekitar Kuala Lumpur",
      biography: {
        ms: "Berpengalaman mengajar Matematik KSSM dan kelas intensif SPM dengan fokus kepada latihan bertahap.",
        en: "Experienced in KSSM Mathematics and SPM intensive classes with step-by-step practice.",
      },
      studentLevelsTaught: ["SPM", "Tingkatan 1-3"],
      teachingLanguages: ["Bahasa Melayu", "English"],
      specialExpertise: ["Matematik Tambahan", "Teknik menjawab"],
    },
    educationLevels: ["Secondary school", "SPM"],
    curriculums: ["KSSM"],
    subjects: ["Matematik", "Matematik Tambahan"],
    categories: ["STEM", "SPM"],
    serviceArea: {
      mode: "both",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      postcode: "50480",
      radiusKm: 15,
      travelFeeAmount: 20,
      acceptsStudentHome: true,
      acceptsTutorLocation: false,
      acceptsPublicLocation: true,
    },
    rates: [
      {
        id: "rate-aisyah-addmath",
        subject: "Matematik Tambahan",
        educationLevel: "SPM",
        mode: "online",
        durationMinutes: 90,
        groupType: "individual",
        sessionType: "standard",
        amount: 90,
      },
    ],
    availability: [
      {
        id: "slot-aisyah-mon",
        dayOfWeek: 1,
        startTime: "20:00",
        endTime: "21:30",
        timezone: "Asia/Kuala_Lumpur",
        mode: "online",
        active: true,
      },
      {
        id: "slot-aisyah-wed",
        dayOfWeek: 3,
        startTime: "18:00",
        endTime: "19:30",
        timezone: "Asia/Kuala_Lumpur",
        mode: "physical",
        active: true,
      },
    ],
    declarations: {
      accurate: true,
      authentic: true,
      terms: true,
      childSafety: true,
      noOffPlatformPayment: true,
      qualityMonitoring: true,
    },
    documents: [
      {
        id: "doc-aisyah-id-front",
        label: { ms: "MyKad bahagian depan", en: "MyKad front" },
        bucketId: "tutor-identity-documents",
        path: "tp-aisyah/identity/front.pdf",
        status: "submitted",
        sizeLabel: "1.2MB",
        private: true,
      },
      {
        id: "doc-aisyah-degree",
        label: { ms: "Sijil ijazah", en: "Degree certificate" },
        bucketId: "tutor-qualification-documents",
        path: "tp-aisyah/qualifications/degree.pdf",
        status: "submitted",
        sizeLabel: "980KB",
        private: true,
      },
    ],
    missingItems: [],
    correctionNotes: [],
    adminNotes: [
      {
        ms: "Semak nombor pendaftaran guru sebelum luluskan.",
        en: "Check teacher registration number before approval.",
      },
    ],
    history: [
      {
        id: "hist-aisyah-draft",
        actorRole: "tutor",
        action: "tutor_created_draft",
        newStatus: "draft",
        at: "2026-07-17T16:00:00+08:00",
        note: { ms: "Tutor memulakan draf permohonan.", en: "Tutor started the application draft." },
      },
      {
        id: "hist-aisyah-submit",
        actorRole: "tutor",
        action: "tutor_submitted_application",
        oldStatus: "draft",
        newStatus: "submitted",
        at: "2026-07-18T09:45:00+08:00",
        note: { ms: "Permohonan dihantar untuk semakan.", en: "Application submitted for review." },
      },
    ],
  },
  {
    id: "app-hakim-2026",
    ownerProfileId: "tutor-hakim-profile",
    tutorProfileId: "tp-hakim",
    status: "changes_requested",
    completionPercent: 82,
    submittedAt: "2026-07-16T11:10:00+08:00",
    reviewedAt: "2026-07-17T14:15:00+08:00",
    updatedAt: "2026-07-17T14:15:00+08:00",
    risk: "medium",
    personal: {
      fullName: "Hakim Yusof",
      displayName: "Cikgu Hakim Yusof",
      gender: "male",
      dateOfBirth: "1994-08-20",
      nationality: "Malaysia",
      state: "Kelantan",
      district: "Kota Bharu",
      postcode: "15200",
      preferredLanguage: "Bahasa Melayu",
      shortBiography: {
        ms: "Tutor Sains yang memberi fokus kepada peta konsep dan latihan topikal untuk menengah rendah.",
        en: "Science tutor focused on concept maps and topical practice for lower secondary learners.",
      },
    },
    identity: {
      documentType: "mykad",
      maskedIdentificationNumber: "940820-03-****",
      consent: true,
    },
    qualifications: [
      {
        id: "qual-hakim-degree",
        level: "Diploma",
        title: "Diploma Sains",
        institution: "Kolej Komuniti Kota Bharu",
        fieldOfStudy: "Sains Gunaan",
        graduationYear: 2016,
        certificateName: "diploma-sains.jpg",
        verificationStatus: "changes_requested",
        adminNotes: {
          ms: "Imej sijil kabur. Muat naik salinan yang lebih jelas.",
          en: "Certificate image is blurry. Upload a clearer copy.",
        },
      },
    ],
    experience: {
      years: 3,
      currentOccupation: "Tutor sambilan",
      isSchoolTeacher: false,
      teachingInstitution: "Kelas tuisyen komuniti",
      biography: {
        ms: "Membantu murid Tingkatan 1-3 memahami eksperimen asas dan istilah Sains.",
        en: "Helps Form 1-3 learners understand basic experiments and Science terminology.",
      },
      studentLevelsTaught: ["Tingkatan 1-3"],
      teachingLanguages: ["Bahasa Melayu"],
      specialExpertise: ["Sains topikal"],
    },
    educationLevels: ["Secondary school"],
    curriculums: ["KSSM"],
    subjects: ["Sains"],
    categories: ["STEM"],
    serviceArea: {
      mode: "online",
      state: "Kelantan",
      district: "Kota Bharu",
      postcode: "15200",
      radiusKm: 0,
      travelFeeAmount: 0,
      acceptsStudentHome: false,
      acceptsTutorLocation: false,
      acceptsPublicLocation: false,
    },
    rates: [
      {
        id: "rate-hakim-science",
        subject: "Sains",
        educationLevel: "Tingkatan 1-3",
        mode: "online",
        durationMinutes: 60,
        groupType: "individual",
        sessionType: "trial",
        amount: 35,
      },
    ],
    availability: [
      {
        id: "slot-hakim-fri",
        dayOfWeek: 5,
        startTime: "21:00",
        endTime: "22:00",
        timezone: "Asia/Kuala_Lumpur",
        mode: "online",
        active: true,
      },
    ],
    declarations: {
      accurate: true,
      authentic: true,
      terms: true,
      childSafety: true,
      noOffPlatformPayment: true,
      qualityMonitoring: true,
    },
    documents: [
      {
        id: "doc-hakim-id",
        label: { ms: "MyKad bahagian depan", en: "MyKad front" },
        bucketId: "tutor-identity-documents",
        path: "tp-hakim/identity/front.pdf",
        status: "submitted",
        sizeLabel: "840KB",
        private: true,
      },
      {
        id: "doc-hakim-diploma",
        label: { ms: "Sijil diploma", en: "Diploma certificate" },
        bucketId: "tutor-qualification-documents",
        path: "tp-hakim/qualifications/diploma.jpg",
        status: "changes_requested",
        sizeLabel: "420KB",
        private: true,
      },
    ],
    missingItems: [{ ms: "Muat naik sijil yang lebih jelas.", en: "Upload a clearer certificate copy." }],
    correctionNotes: [{ ms: "Sijil akademik kabur dan perlu diganti.", en: "Academic certificate is blurry and must be replaced." }],
    adminNotes: [{ ms: "Jangan luluskan sehingga sijil baharu diterima.", en: "Do not approve until the new certificate is received." }],
    history: [
      {
        id: "hist-hakim-submit",
        actorRole: "tutor",
        action: "tutor_submitted_application",
        oldStatus: "draft",
        newStatus: "submitted",
        at: "2026-07-16T11:10:00+08:00",
        note: { ms: "Permohonan dihantar.", en: "Application submitted." },
      },
      {
        id: "hist-hakim-review",
        actorRole: "admin",
        action: "admin_requested_changes",
        oldStatus: "under_review",
        newStatus: "changes_requested",
        at: "2026-07-17T14:15:00+08:00",
        note: { ms: "Admin meminta sijil yang lebih jelas.", en: "Admin requested a clearer certificate." },
      },
    ],
  },
  {
    id: "app-nadia-2026",
    ownerProfileId: "tutor-nadia-profile",
    tutorProfileId: "tp-nadia",
    status: "approved",
    completionPercent: 100,
    submittedAt: "2026-07-10T08:30:00+08:00",
    reviewedAt: "2026-07-11T10:00:00+08:00",
    approvedAt: "2026-07-11T10:00:00+08:00",
    updatedAt: "2026-07-11T10:00:00+08:00",
    risk: "low",
    personal: {
      fullName: "Nadia Salleh",
      displayName: "Cikgu Nadia Salleh",
      gender: "female",
      dateOfBirth: "1988-01-22",
      nationality: "Malaysia",
      state: "Selangor",
      district: "Subang Jaya",
      postcode: "47500",
      preferredLanguage: "Bahasa Melayu",
      shortBiography: {
        ms: "Pakar Matematik Tambahan SPM dengan teknik langkah demi langkah untuk murid sasaran A.",
        en: "SPM Additional Mathematics specialist with step-by-step techniques for A-target learners.",
      },
    },
    identity: {
      documentType: "mykad",
      maskedIdentificationNumber: "880122-10-****",
      consent: true,
    },
    qualifications: [
      {
        id: "qual-nadia-master",
        level: "Sarjana",
        title: "Sarjana Pendidikan Matematik",
        institution: "Universiti Kebangsaan Malaysia",
        fieldOfStudy: "Pendidikan Matematik",
        graduationYear: 2014,
        certificateName: "masters-certificate.pdf",
        verificationStatus: "verified",
        adminNotes: {
          ms: "Kelayakan disahkan.",
          en: "Qualification verified.",
        },
      },
    ],
    experience: {
      years: 12,
      currentOccupation: "Guru Matematik Tambahan",
      isSchoolTeacher: true,
      teachingInstitution: "SMK sekitar Selangor",
      biography: {
        ms: "Berpengalaman membimbing kelas peperiksaan dan klinik Add Math intensif.",
        en: "Experienced in exam classes and intensive Additional Mathematics clinics.",
      },
      studentLevelsTaught: ["SPM"],
      teachingLanguages: ["Bahasa Melayu", "English"],
      specialExpertise: ["Matematik Tambahan", "KBAT"],
    },
    educationLevels: ["Secondary school", "SPM"],
    curriculums: ["KSSM"],
    subjects: ["Matematik Tambahan"],
    categories: ["STEM", "SPM"],
    serviceArea: {
      mode: "both",
      state: "Selangor",
      district: "Subang Jaya",
      postcode: "47500",
      radiusKm: 20,
      travelFeeAmount: 25,
      acceptsStudentHome: true,
      acceptsTutorLocation: true,
      acceptsPublicLocation: true,
    },
    rates: [
      {
        id: "rate-nadia-standard",
        subject: "Matematik Tambahan",
        educationLevel: "SPM",
        mode: "physical",
        durationMinutes: 90,
        groupType: "individual",
        sessionType: "standard",
        amount: 110,
      },
    ],
    availability: [
      {
        id: "slot-nadia-tue",
        dayOfWeek: 2,
        startTime: "18:30",
        endTime: "20:00",
        timezone: "Asia/Kuala_Lumpur",
        mode: "physical",
        active: true,
      },
    ],
    declarations: {
      accurate: true,
      authentic: true,
      terms: true,
      childSafety: true,
      noOffPlatformPayment: true,
      qualityMonitoring: true,
    },
    documents: [
      {
        id: "doc-nadia-id",
        label: { ms: "MyKad bahagian depan", en: "MyKad front" },
        bucketId: "tutor-identity-documents",
        path: "tp-nadia/identity/front.pdf",
        status: "verified",
        sizeLabel: "1.1MB",
        private: true,
      },
      {
        id: "doc-nadia-master",
        label: { ms: "Sijil sarjana", en: "Master certificate" },
        bucketId: "tutor-qualification-documents",
        path: "tp-nadia/qualifications/master.pdf",
        status: "verified",
        sizeLabel: "1.4MB",
        private: true,
      },
    ],
    missingItems: [],
    correctionNotes: [],
    adminNotes: [{ ms: "Profil selamat untuk paparan marketplace.", en: "Profile is safe for marketplace display." }],
    history: [
      {
        id: "hist-nadia-submit",
        actorRole: "tutor",
        action: "tutor_submitted_application",
        oldStatus: "draft",
        newStatus: "submitted",
        at: "2026-07-10T08:30:00+08:00",
        note: { ms: "Permohonan dihantar.", en: "Application submitted." },
      },
      {
        id: "hist-nadia-approve",
        actorRole: "admin",
        action: "admin_approved_application",
        oldStatus: "under_review",
        newStatus: "approved",
        at: "2026-07-11T10:00:00+08:00",
        note: { ms: "Permohonan diluluskan.", en: "Application approved." },
      },
    ],
  },
];
